select * from all_users;

-- hr 사용자의 계정을 풀고 비밀번호를 hr로 지정
ALTER USER hr IDENTIFIED BY hr account unlock;

--shop 생성(스키마 생성)
CREATE USER shop IDENTIFIED BY 12345;
create user javadb2 indentified by 12345;
--권한 부여
--CONNECT => CREATE SESSION
--RESOURCE => CREATE TRIGGER,CREATE SEQUENCE,CREATE PROCEDURE, CREATE TABLE.....
GRANT CONNECT,RESOURCE TO shop;
ALTER USER JAVADB IDENTIFIED BY JAVADB account unlock;
CREATE USER javadb IDENTIFIED BY 12345;
GRANT CONNECT,RESOURCE TO JAVADB;
GRANT RESOURCE TO JAVADB;
grant sysdba to JAVADB;
--VIEW 권한 부여
GRANT CREATE VIEW TO SCOTT;


--DBA_ : 데이터베이스 관리 권한을 가진 사용자만 조회가능
SELECT * FROM DBA_TABLES;



--사용자 생성
CREATE USER TEST IDENTIFIED BY 12345;
--user TEST lacks CREATE SESSION privilege; logon denied
GRANT CREATE SESSION TO TEST;

--사용자 비밀번호 변경
ALTER USER TEST IDENTIFIED BY 54321;
--사용자 삭지
DROP USER TEST;
